universe = vanilla
executable = /home/ethan.payne/projects/GWPhotonCounting/projects/PM_EOS/hierarchical_EOS/injection_noise_submit.sh
log = /home/ethan.payne/projects/GWPhotonCounting/projects/PM_EOS/hierarchical_EOS/logs/$(id)_noise.log
error = /home/ethan.payne/projects/GWPhotonCounting/projects/PM_EOS/hierarchical_EOS/logs/$(id)_noise.err
output = /home/ethan.payne/projects/GWPhotonCounting/projects/PM_EOS/hierarchical_EOS/logs/$(id)_noise.out
arguments = $(id)
accounting_group = ligo.dev.o4.cbc.pe.lalinference
notification = error
request_memory = 8192
request_disk = 1
getenv = true
max_retries = 5
queue 1
